//
//  AstronomicalObjectItem.swift
//  terrela
//
//  Created by Eric Morales on 3/20/21.
//

import SwiftUI

struct AstronomicalObjectsItem: Identifiable {
    
    var id = UUID().uuidString
    // both image and name are the same
    var name: String
    var shortDescription: String
    var firstFactTitle: String
    var firstFactInfo: String
    var secondFactTitle: String
    var secondFactInfo: String
    var thirdFactTitle: String
    var thirdFactInfo: String
    var fourthFactTitle: String
    var fourthFactInfo: String
    var descriptionParagraph1: String
    var descriptionParagraph2: String
    var descriptionParagraph3: String
}

var astronomicalObjects = [
    
    AstronomicalObjectsItem(name: "Solar System", shortDescription: "A planetary system located in an outer spiral arm of the Milky Way galaxy.", firstFactTitle: "Stars", firstFactInfo: "1", secondFactTitle: "Age", secondFactInfo: "~4.5 billion years", thirdFactTitle: "Nearest star", thirdFactInfo: "Proxima Centauri", fourthFactTitle: "Location", fourthFactInfo: "Milky Way Galaxy", descriptionParagraph1: "There are many planetary systems like ours in the universe, with planets orbiting a host star. Our planetary system is named the 'solar' system because our Sun is named Sol, after the Latin word for Sun, 'solis,' and anything related to the Sun we call 'solar.'", descriptionParagraph2: "Our planetary system is located in an outer spiral arm of the Milky Way galaxy.", descriptionParagraph3: "Our solar system consists of our star, the Sun, and everything bound to it by gravity — the planets Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus and Neptune, dwarf planets such as Pluto, dozens of moons and millions of asteroids, comets and meteoroids. Beyond our own solar system, we have discovered thousands of planetary systems orbiting other stars in the Milky Way."),
    
    AstronomicalObjectsItem(name: "Sun", shortDescription: "The Sun is a yellow dwarf star.", firstFactTitle: "Start-Type", firstFactInfo: "Yellow Dwarf", secondFactTitle: "Distance from Earth", secondFactInfo: "1 AU", thirdFactTitle: "Surface Temperature", thirdFactInfo: "5,505 °C", fourthFactTitle: "Mass", fourthFactInfo: "99.8% of the Solar System", descriptionParagraph1: "The Sun is a yellow dwarf star, a hot ball of glowing gases at the heart of our solar system.", descriptionParagraph2: "Its gravity holds the solar system together, keeping everything from the biggest planets to the smallest particles of debris in its orbit. Electric currents in the Sun generate a magnetic field that is carried out through the solar system by the solar wind—a stream of electrically charged gas blowing outward from the Sun in all directions.", descriptionParagraph3: "The connection and interactions between the Sun and Earth drive the seasons, ocean currents, weather, climate, radiation belts and aurorae. Though it is special to us, there are billions of stars like our Sun scattered across the Milky Way galaxy."),
    
    AstronomicalObjectsItem(name: "Mercury", shortDescription: "The smallest planet in our solar system and nearest to the Sun.", firstFactTitle: "Day", firstFactInfo: "176 Earth days", secondFactTitle: "Year", secondFactInfo: "88 Earth day", thirdFactTitle: "Planet Type", thirdFactInfo: "Terrestrial", fourthFactTitle: "Moons", fourthFactInfo: "0", descriptionParagraph1: "The smallest planet in our solar system and nearest to the Sun, Mercury is only slightly larger than Earth's Moon.", descriptionParagraph2: "From the surface of Mercury, the Sun would appear more than three times as large as it does when viewed from Earth, and the sunlight would be as much as seven times brighter. Despite its proximity to the Sun, Mercury is not the hottest planet in our solar system – that title belongs to nearby Venus, thanks to its dense atmosphere.", descriptionParagraph3: "Because of Mercury's elliptical—egg-shaped—orbit and sluggish rotation, the morning Sun appears to rise briefly, set and rise again from some parts of the planet's surface. The same thing happens in reverse at sunset."),

    AstronomicalObjectsItem(name: "Venus", shortDescription: "Venus has been called Earth's twin.", firstFactTitle: "Day", firstFactInfo: "243 Earth days", secondFactTitle: "Year", secondFactInfo: "225 Earth days", thirdFactTitle: "Planet Type", thirdFactInfo: "Terrestrial", fourthFactTitle: "Moons", fourthFactInfo: "0", descriptionParagraph1: "Similar in size and structure to Earth, Venus has been called Earth's twin. These are not identical twins, however – there are radical differences between the two worlds.", descriptionParagraph2: "Venus has a thick, toxic atmosphere filled with carbon dioxide and it’s perpetually shrouded in thick, yellowish clouds of mostly sulfuric acid that trap heat, causing a runaway greenhouse effect. It’s the hottest planet in our solar system, even though Mercury is closer to the Sun. Venus has crushing air pressure at its surface – more than 90 times that of Earth – similar to the pressure you'd encounter a mile below the ocean on Earth.", descriptionParagraph3: "Venus was the first planet to be explored by a spacecraft – NASA’s Mariner 2 successfully flew by and scanned the cloud-covered world on Dec. 14, 1962. Since then, numerous spacecraft from the U.S. and other space agencies have explored Venus, including NASA’s Magellan, which mapped the planet's surface with radar. The former Soviet Union is the only nation to land on the surface of Venus to date, though the spacecraft did not survive long in the harsh environment."),

    AstronomicalObjectsItem(name: "Earth", shortDescription: "Our home planet is the third planet from the Sun.", firstFactTitle: "Earth", firstFactInfo: "23.9 hours", secondFactTitle: "Year", secondFactInfo: "365.25", thirdFactTitle: "Planet Type", thirdFactInfo: "Terrestrial", fourthFactTitle: "Moons", fourthFactInfo: "1", descriptionParagraph1: "Our home planet is the third planet from the Sun, and the only place we know of so far that’s inhabited by living things.", descriptionParagraph2: "While Earth is only the fifth largest planet in the solar system, it is the only world in our solar system with liquid water on the surface. Just slightly larger than nearby Venus, Earth is the biggest of the four planets closest to the Sun, all of which are made of rock and metal.", descriptionParagraph3: "The name Earth is at least 1,000 years old. All of the planets, except for Earth, were named after Greek and Roman gods and goddesses. However, the name Earth is a Germanic word, which simply means 'the ground.'"),

    AstronomicalObjectsItem(name: "Mars", shortDescription: "Mars is a dusty, cold, desert world with a very thin atmosphere.", firstFactTitle: "Day", firstFactInfo: "24.6 hours", secondFactTitle: "Year", secondFactInfo: "687 Earth days", thirdFactTitle: "Planet Type", thirdFactInfo: "Terrestrial", fourthFactTitle: "Moons", fourthFactInfo: "2", descriptionParagraph1: "The fourth planet from the Sun, Mars is a dusty, cold, desert world with a very thin atmosphere.", descriptionParagraph2: "This dynamic planet has seasons, polar ice caps, canyons, extinct volcanoes, and evidence that it was even more active in the past.", descriptionParagraph3: "Mars is one of the most explored bodies in our solar system, and it's the only planet where we've sent rovers to roam the alien landscape. NASA currently has three spacecraft in orbit, and it has one rover and one lander on the surface. NASA launched the next-generation Perseverance rover to Mars on July 30, 2020. India and ESA have spacecraft in orbit above Mars. These robotic explorers have found lots of evidence that Mars was much wetter and warmer, with a thicker atmosphere, billions of years ago."),
    
    AstronomicalObjectsItem(name: "Jupiter", shortDescription: "The largest planet in the solar system", firstFactTitle: "Day", firstFactInfo: "9.93 hours", secondFactTitle: "Year", secondFactInfo: "11.86 Earth years", thirdFactTitle: "Planet Type", thirdFactInfo: "Gas Giant", fourthFactTitle: "Moons", fourthFactInfo: "79", descriptionParagraph1: "Jupiter has a long history surprising scientists—all the way back to 1610 when Galileo Galilei found the first moons beyond Earth. That discovery changed the way we see the universe.", descriptionParagraph2: "Fifth in line from the Sun, Jupiter is, by far, the largest planet in the solar system – more than twice as massive as all the other planets combined.", descriptionParagraph3: "Jupiter's familiar stripes and swirls are actually cold, windy clouds of ammonia and water, floating in an atmosphere of hydrogen and helium. Jupiter’s iconic Great Red Spot is a giant storm bigger than Earth that has raged for hundreds of years."),

    AstronomicalObjectsItem(name: "Saturn", shortDescription: "The second largest planet in our solar system.", firstFactTitle: "Day", firstFactInfo: "10.7", secondFactTitle: "Year", secondFactInfo: "29 Earth years", thirdFactTitle: "Planet Type", thirdFactInfo: "Gas Giant", fourthFactTitle: "Moons", fourthFactInfo: "82", descriptionParagraph1: "Saturn is the sixth planet from the Sun and the second largest planet in our solar system.", descriptionParagraph2: "Adorned with thousands of beautiful ringlets, Saturn is unique among the planets. It is not the only planet to have rings—made of chunks of ice and rock—but none are as spectacular or as complicated as Saturn's.", descriptionParagraph3: "Like fellow gas giant Jupiter, Saturn is a massive ball made mostly of hydrogen and helium."),

    AstronomicalObjectsItem(name: "Uranus", shortDescription: "The first planet found with the aid of a telescope.", firstFactTitle: "Day", firstFactInfo: "17 hours 14 minutes", secondFactTitle: "Year", secondFactInfo: "84 Earth years", thirdFactTitle: "Planet Type", thirdFactInfo: "Ice Giant", fourthFactTitle: "Moons", fourthFactInfo: "27", descriptionParagraph1: "The first planet found with the aid of a telescope, Uranus was discovered in 1781 by astronomer William Herschel, although he originally thought it was either a comet or a star.", descriptionParagraph2: "It was two years later that the object was universally accepted as a new planet, in part because of observations by astronomer Johann Elert Bode. Herschel tried unsuccessfully to name his discovery Georgium Sidus after King George III. Instead the scientific community accepted Bode's suggestion to name it Uranus, the Greek god of the sky, as suggested by Bode.​", descriptionParagraph3: "Uranus' unique sideways rotation makes for weird seasons. The planet's north pole experiences 21 years of nighttime in winter, 21 years of daytime in summer and 42 years of day and night in the spring and fall."),

    AstronomicalObjectsItem(name: "Neptune", shortDescription: "Ice giant Neptune is the most distant planet in our solar system.", firstFactTitle: "Day", firstFactInfo: "16", secondFactTitle: "Year", secondFactInfo: "165 Earth years", thirdFactTitle: "Planet Type", thirdFactInfo: "Ice Giant", fourthFactTitle: "Moons", fourthFactInfo: "14", descriptionParagraph1: "Dark, cold and whipped by supersonic winds, ice giant Neptune is the eighth and most distant planet in our solar system.", descriptionParagraph2: "More than 30 times as far from the Sun as Earth, Neptune is the only planet in our solar system not visible to the naked eye and the first predicted by mathematics before its discovery. In 2011 Neptune completed its first 165-year orbit since its discovery in 1846.", descriptionParagraph3: "NASA's Voyager 2 is the only spacecraft to have visited Neptune up close. It flew past in 1989 on its way out of the solar system.")

]


