//
//  MissionsItems.swift
//  terrela
//
//  Created by Eric Morales on 3/21/21.
//

import SwiftUI

struct MissionsItems: Identifiable {
    
    var id = UUID().uuidString
    // both image and name are the same
    var name: String
    var shortDescription: String
    var firstGoal: String
    var secondGoal: String
    var thirdGoal: String
    var descriptionParagraph1: String
    var descriptionParagraph2: String
    var descriptionParagraph3: String
}

var missions = [
    
    MissionsItems(name: "Artemis Program", shortDescription: "NASA mission to land American astronauts, including the first woman on the Moon", firstGoal: "Demostrate Technologies", secondGoal: "Establishing American Ladership", thirdGoal: "Broaden Parnerships", descriptionParagraph1: "NASA is committed to landing American astronauts, including the first woman and the next man, on the Moon by 2024. Through the agency’s Artemis lunar exploration program, we will use innovative new technologies and systems to explore more of the Moon than ever before. We will collaborate with our commercial and international partners to establish sustainable missions by 2028. And then we will use what we learn on and around the Moon to take the next giant leap – sending astronauts to Mars.", descriptionParagraph2: "NASA’s powerful new rocket, the Space Launch System (SLS), will send astronauts aboard the Orion spacecraft nearly a quarter million miles from Earth to lunar orbit. Astronauts will dock Orion at the Gateway and transfer to a human landing system for expeditions to the surface of the Moon. They will return to the orbital outpost to board Orion again before returning safely to Earth.", descriptionParagraph3: "The agency will fly two missions around the Moon to test its deep space exploration systems. NASA is working toward launching Artemis I, an uncrewed flight to test the SLS and Orion spacecraft together, followed by the Artemis II mission, the first SLS and Orion test flight with crew. NASA will land astronauts on the Moon by 2024 on the Artemis III mission and about once a year thereafter. "),
    
    MissionsItems(name: "Apollo Program", shortDescription: "Program that succeeded in landing the first human on the Moon.", firstGoal: "Win Space Race", secondGoal: "Preminances in Space", thirdGoal: "Explore the Moon", descriptionParagraph1: "The Apollo program, also known as Project Apollo, was the third United States human spaceflight program carried out by the National Aeronautics and Space Administration (NASA), which succeeded in landing the first humans on the Moon from 1969 to 1972. It was first conceived during Dwight D. Eisenhower's administration as a three-person spacecraft to follow the one-person Project Mercury, which put the first Americans in space. Apollo was later dedicated to President John F. Kennedy's national goal for the 1960s of 'landing a man on the Moon and returning him safely to the Earth' in an address to Congress on May 25, 1961. It was the third US human spaceflight program to fly, preceded by the two-person Project Gemini conceived in 1961 to extend spaceflight capability in support of Apollo.", descriptionParagraph2: "Kennedy's goal was accomplished on the Apollo 11 mission when astronauts Neil Armstrong and Buzz Aldrin landed their Apollo Lunar Module (LM) on July 20, 1969, and walked on the lunar surface, while Michael Collins remained in lunar orbit in the command and service module (CSM), and all three landed safely on Earth on July 24. Five subsequent Apollo missions also landed astronauts on the Moon, the last, Apollo 17, in December 1972. In these six spaceflights, twelve people walked on the Moon. ", descriptionParagraph3: "Apollo ran from 1961 to 1972, with the first crewed flight in 1968. It encountered a major setback in 1967 when an Apollo 1 cabin fire killed the entire crew during a prelaunch test. After the first successful landing, sufficient flight hardware remained for nine follow-on landings with a plan for extended lunar geological and astrophysical exploration."),

    MissionsItems(name: "Curiosity Mars Rover", shortDescription: "Explore and assess whether Mars ever had an enviroment able to support life.", firstGoal: "Land Heavy Rover", secondGoal: "Demostrate a Precision of 12 mi", thirdGoal: "Demostrate long-range mobility", descriptionParagraph1: "Curiosity was designed to assess whether Mars ever had an environment able to support small life forms called microbes. In other words, its mission is to determine the planet's 'habitability.'", descriptionParagraph2: "To find out, the rover carries the biggest, most advanced suite of instruments for scientific studies ever sent to the martian surface. The rover will analyze samples scooped from the soil and drilled from rocks. The record of the planet's climate and geology is essentially 'written in the rocks and soil' -- in their formation, structure, and chemical composition. The rover's onboard laboratory will study rocks, soils, and the local geologic setting in order to detect chemical building blocks of life (e.g., forms of carbon) on Mars and will assess what the martian environment was like in the past.", descriptionParagraph3: "Mars Science Laboratory will rely on new technological innovations, especially for landing. The spacecraft descended on a parachute and then, during the final seconds prior to landing, lowered the upright rover on a tether to the surface, much like a sky crane. Now on the surface, the rover will be able to roll over obstacles up to 75 centimeters (29 inches) high and travel up to 90 meters (295 feet) per hour. On average, the rover is expected to travel about 30 meters (98 feet) per hour, based on power levels, slippage, steepness of the terrain, visibility, and other variables."),

    MissionsItems(name: "Mars Perseverance Rover", shortDescription: "Expolre and serach for sings of ancient microbial life.", firstGoal: "Looking for habitability", secondGoal: "Seeking Biosignatures", thirdGoal: "Caching Samples", descriptionParagraph1: "The Mars 2020 Perseverance Rover will search for signs of ancient microbial life, which will advance NASA's quest to explore the past habitability of Mars. The rover has a drill to collect core samples of Martian rock and soil, then store them in sealed tubes for pickup by a future mission that would ferry them back to Earth for detailed analysis. Perseverance will also test technologies to help pave the way for future human exploration of Mars.", descriptionParagraph2: "Strapped to the rover's belly for the journey to Mars is a technology demonstration — the Mars Helicopter, Ingenuity, may achieve a 'Wright Brothers moment' by testing the first powered flight on the Red Planet.", descriptionParagraph3: "There are several ways that the mission helps pave the way for future human expeditions to Mars and demonstrates technologies that may be used in those endeavors. These include testing a method for producing oxygen from the Martian atmosphere, identifying other resources (such as subsurface water), improving landing techniques, and characterizing weather, dust, and other potential environmental conditions that could affect future astronauts living and working on Mars."),

    MissionsItems(name: "Hubble Space Telescope", shortDescription: "Space-base observatory, which has revolutionized astronomy.", firstGoal: "Chance to study the universe", secondGoal: "Evade atmosphere to see space", thirdGoal: "Steady images", descriptionParagraph1: "NASA’s Hubble Space Telescope is the first astronomical observatory placed into orbit around Earth with the ability to record images in wavelengths of light spanning from ultraviolet to near-infrared. Hubble continues to operate high above the blurring effects of Earth’s atmosphere.", descriptionParagraph2: "Hubble was launched on April 24, 1990, in the cargo bay of Space Shuttle Discovery and deployed the following day. Hubble continues to provide images of unprecedented resolution from which many new and exciting discoveries have been made.", descriptionParagraph3: "Hubble is a Cassegrain reflector telescope and the first telescope designed to be repaired in space"),

    MissionsItems(name: "James Webb Space Telescope", shortDescription: "Space-base observatory that will be the next premier observatory for the next decade.", firstGoal: "Detect frist stars/galaxies", secondGoal: "Help search for life", thirdGoal: "Watch how galaxies grow", descriptionParagraph1: "The James Webb Space Telescope (sometimes called JWST or Webb) will be a large infrared telescope with a 6.5-meter primary mirror. The telescope will be launched on an Ariane 5 rocket from French Guiana in 2021.", descriptionParagraph2: "The Webb telescope will be the premier observatory of the next decade, serving thousands of astronomers worldwide. It will study every phase in the history of our Universe, ranging from the first luminous glows after the Big Bang, to the formation of solar systems capable of supporting life on planets like Earth, to the evolution of our own Solar System.", descriptionParagraph3: "The Webb telescope was formerly known as the 'Next Generation Space Telescope' (NGST); it was renamed in September 2002 after a former NASA administrator, James Webb."),

    MissionsItems(name: "Parker Solar Probe", shortDescription: "Humanity's first visit to a Star.", firstGoal: "Fly the closest to the Sun", secondGoal: "24 Orbits around Sun", thirdGoal: "Close aproach at ~4 million mi", descriptionParagraph1: "NASA's Parker Solar Probe is on a mission to 'touch the Sun.' The spacecraft is flying closer to the Sun’s surface than any spacecraft before it. The mission will revolutionize our understanding of the Sun.", descriptionParagraph2: "During its journey, the mission will provide answers to long-standing questions that have puzzled scientists for more than 60 years: Why is the corona much hotter than the Sun's surface (the photosphere)? How does the solar wind accelerate? What are the sources of high-energy solar particles? ", descriptionParagraph3: "We live in the Sun's atmosphere and this mission will help scientists better understand the Sun's impact on Earth."),

    MissionsItems(name: "Voyager", shortDescription: "No spacecraft has gone farther than any of NASA's Voyagers.", firstGoal: "Extend exploration", secondGoal: "Learn outer solar system", thirdGoal: "Explore Jupyter and Saturn", descriptionParagraph1: "The twin Voyager 1 and 2 spacecraft are exploring where nothing from Earth has flown before. Continuing on their over-40-year journey since their 1977 launches, they each are much farther away from Earth and the sun than Pluto. In August 2012, Voyager 1 made the historic entry into interstellar space, the region between stars, filled with material ejected by the death of nearby stars millions of years ago. Scientists hope to learn more about this region from Voyager 2's November 2018 exit from the heliosphere into interstellar space. Both spacecraft are still sending scientific information about their surroundings through the Deep Space Network, or DSN.", descriptionParagraph2: "The primary mission was the exploration of Jupiter and Saturn. After making a string of discoveries there -- such as active volcanoes on Jupiter's moon Io and intricacies of Saturn's rings -- the mission was extended. Voyager 2 went on to explore Uranus and Neptune, and is still the only spacecraft to have visited those outer planets. The adventurers' current mission, the Voyager Interstellar Mission (VIM), will explore the outermost edge of the Sun's domain. And beyond.", descriptionParagraph3: "The mission objective of the Voyager Interstellar Mission (VIM) is to extend the NASA exploration of the solar system beyond the neighborhood of the outer planets to the outer limits of the Sun's sphere of influence, and possibly beyond. This extended mission is continuing to characterize the outer solar system environment and search for the heliopause boundary, the outer limits of the Sun's magnetic field and outward flow of the solar wind. Penetration of the heliopause boundary between the solar wind and the interstellar medium will allow measurements to be made of the interstellar fields, particles and waves unaffected by the solar wind."),

    MissionsItems(name: "OSIRIS-REx", shortDescription: "Help investigate how planets formed and how life began.", firstGoal: "Visit asteroid", secondGoal: "Obtain samples", thirdGoal: "Return samples", descriptionParagraph1: "OSIRIS-REx (Origins, Spectral Interpretation, Resource Identification, Security, Regolith Explorer) is a NASA asteroid-study and sample-return mission. The mission's primary goal is to obtain a sample of at least 60 g (2.1 oz) from 101955 Bennu, a carbonaceous near-Earth asteroid, and return the sample to Earth for a detailed analysis. The material returned is expected to enable scientists to learn more about the formation and evolution of the Solar System, its initial stages of planet formation, and the source of organic compounds that led to the formation of life on Earth.", descriptionParagraph2: "OSIRIS-REx was launched on 8 September 2016, flew past Earth on 22 September 2017, and rendezvoused with Bennu on 3 December 2018. It spent the next several months analyzing the surface to find a suitable site from which to extract a sample. On 20 October 2020, OSIRIS-REx approached Bennu and successfully collected a sample. Though some of the sample escaped when the flap that should have closed the sampler head was jammed open by larger rocks, NASA is confident that they were able to retain between 400 g and over 1 kg of sample material, well in excess of the 60 g (2.1 oz) minimum target mass. OSIRIS-REx is expected to return with its sample to Earth on 24 September 2023.", descriptionParagraph3: "The cost of the mission is approximately US$800 million,[19] not including the Atlas V launch vehicle, which is about US$183.5 million. It is the third planetary science mission selected in the New Frontiers program, after Juno and New Horizons. The principal investigator is Dante Lauretta from the University of Arizona. If successful, OSIRIS-REx will be the first United States spacecraft to return samples from an asteroid. The Japanese probe Hayabusa returned samples from 25143 Itokawa in 2010, and Hayabusa2 returned from 162173 Ryugu in December 2020.")

]
