//
//  RocketsItems.swift
//  terrela
//
//  Created by Eric Morales on 3/21/21.
//

import SwiftUI

struct RocketsItems: Identifiable {
    
    var id = UUID().uuidString
    // both image and name are the same
    var name: String
    var shortDescription: String
    var firstFactTitle: String
    var firstFactInfo: String
    var secondFactTitle: String
    var secondFactInfo: String
    var thirdFactTitle: String
    var thirdFactInfo: String
    var fourthFactTitle: String
    var fourthFactInfo: String
    var descriptionParagraph1: String
    var descriptionParagraph2: String
    var descriptionParagraph3: String
}

var rockets = [
    
    RocketsItems(name: "Falcon 9", shortDescription: "First Orbital Class Rocket capable of reflight.", firstFactTitle: "Height", firstFactInfo: "70 m", secondFactTitle: "Diameter", secondFactInfo: "3.7 m", thirdFactTitle: "Stages", thirdFactInfo: "2", fourthFactTitle: "Thrust", fourthFactInfo: "7,607 kN", descriptionParagraph1: "Falcon 9 is a partially reusable two-stage-to-orbit medium-lift launch vehicle designed and manufactured by SpaceX in the United States. Both the first and second stages are powered by SpaceX Merlin engines, using cryogenic liquid oxygen and rocket-grade kerosene (RP-1) as propellants. Its name is derived from the fictional Star Wars spacecraft, the Millennium Falcon, and the nine Merlin engines of the rocket's first stage.", descriptionParagraph2: "The rocket evolved with versions v1.0 (2010–2013), v1.1 (2013–2016), v1.2 'Full Thrust' (2015–present), including the Block 5 Full Thrust variant, flying since May 2018. Unlike most rockets in service, which are expendable launch systems, since the introduction of the Full Thrust version, Falcon 9 is partially reusable, with the first stage capable of re-entering the atmosphere and landing vertically after separating from the second stage. This feat was achieved for the first time on flight 20 in December 2015.", descriptionParagraph3: "Falcon 9 can lift payloads of up to 22,800 kilograms (50,300 lb) to low Earth orbit (LEO), 8,300 kg (18,300 lb) to geostationary transfer orbit (GTO) when expended, and 5,500 kg (12,100 lb) to GTO when the first stage is recovered."),
    
    RocketsItems(name: "Falcon Heavy", shortDescription: "The world’s most powerful operational rocket.", firstFactTitle: "Height", firstFactInfo: "70 m", secondFactTitle: "Diameter", secondFactInfo: "12.2 m", thirdFactTitle: "Stages", thirdFactInfo: "2+", fourthFactTitle: "Thrust", fourthFactInfo: "15.2 MN", descriptionParagraph1: "Falcon Heavy is a partially reusable heavy-lift launch vehicle designed and manufactured by SpaceX. It is derived from the Falcon 9 vehicle and consists of a strengthened Falcon 9 first stage as the center core with two additional Falcon 9-like first stages as strap-on boosters. Falcon Heavy has the highest payload capacity of any currently operational launch vehicle, and the third-highest capacity of any rocket ever to reach orbit, trailing the Saturn V and Energia.", descriptionParagraph2: "SpaceX conducted Falcon Heavy's maiden launch on 6 February 2018. The rocket carried a Tesla Roadster belonging to SpaceX founder Elon Musk, with a dummy dubbed 'Starman' in the driver's seat, as a dummy payload. The second Falcon Heavy launch occurred on 11 April 2019 and all three booster rockets successfully returned to Earth. The third Falcon Heavy launch successfully occurred on 25 June 2019. Since then, Falcon Heavy has been certified for the National Security Space Launch (NSSL) program.", descriptionParagraph3: "Falcon Heavy was designed to be able to carry humans into space beyond low Earth orbit, although as of February 2018, SpaceX has confirmed that they will not transport people on Falcon Heavy, nor pursue the human-rating certification process to transport NASA astronauts. Both Falcon Heavy and Falcon 9 will eventually be superseded by the in-development Starship launch system."),
    
    RocketsItems(name: "Starship", shortDescription: "Will become the world's most powerfull launch vehicle ever developed.", firstFactTitle: "Height", firstFactInfo: "120 m", secondFactTitle: "Diameter", secondFactInfo: "9 m", thirdFactTitle: "Stages", thirdFactInfo: "2", fourthFactTitle: "Thrust", fourthFactInfo: "88 MN", descriptionParagraph1: "SpaceX’s Starship spacecraft and Super Heavy rocket (collectively referred to as Starship) represent a fully reusable transportation system designed to carry both crew and cargo to Earth orbit, the Moon, Mars and beyond. Starship will be the world’s most powerful launch vehicle ever developed, with the ability to carry in excess of 100 metric tonnes to Earth orbit.", descriptionParagraph2: "Engine development started in 2012, and Starship development began in 2016 as a self-funded private spaceflight project. Testing of the second stage Starship began in 2019 as part of an extensive development program to prove out launch-and-landing and iterate on a variety of design details, particularly with respect to the vehicle's atmospheric reentry. The first prototype, nicknamed Starhopper, made low-altitude, low-velocity flight testing of vertical launches and landings in March 2020. On 9 December 2020, Starship prototype SN8 performed the first high-altitude test flight, demonstrating most of the atmospheric re-entry maneuvers. The test was deemed a success, although a hard landing caused the explosion of the prototype. More prototype Starships have been built and more are under construction as the iterative design progresses. All test articles have a 9 m (30 ft)-diameter stainless steel hull. ", descriptionParagraph3: "In June 2019, SpaceX indicated they could potentially launch commercial payloads using Starship as early as 2021. In April 2020, NASA selected a modified crew-rated Starship system as one of three potential lunar landing system design concepts to receive funding for a 10-month-long initial design phase for the NASA Artemis program. On March 3 2021, SpaceX successfully conducted a soft landing for Starship prototype SN10 during a test flight. Although SN10 exploded shortly after touchdown on its landing pad due to a suspected methane leak, the flight marked the first time a Starship prototype successfully landed after attempting the bellyflop maneuver. "),
    
    RocketsItems(name: "Electron", shortDescription: "Electron is the only reusable orbital-class small rocket.", firstFactTitle: "Height", firstFactInfo: "18 m", secondFactTitle: "Diameter", secondFactInfo: "1.2 m", thirdFactTitle: "Stages", thirdFactInfo: "2 + Kick Stage", fourthFactTitle: "Thrust", fourthFactInfo: "249 kN", descriptionParagraph1: "Electron is a two-stage (sometimes three-stage) partially recoverable orbital launch vehicle developed by Rocket Lab, an American aerospace company founded in New Zealand with a wholly owned New Zealand subsidiary. Electron was developed to service the commercial small satellite launch market. Its Rutherford engines are the first electric-pump-fed engine to power an orbital-class rocket. Although the rocket is designed to be expendable, Rocket Lab considers adding capabilities to reuse the first stage of Electron and has demonstrated a capability to recover the booster.", descriptionParagraph2: "In December 2016, Electron completed flight qualification. The first rocket was launched on 25 May 2017, reaching space but not achieving orbit due to a glitch in communication equipment on the ground. During its second flight on 21 January 2018, Electron reached orbit and deployed three CubeSats. The first commercial launch of Electron, and the third launch overall, occurred on 11 November 2018.", descriptionParagraph3: "Electron uses two stages with the same diameter (1.2 m (3 ft 11 in)) filled with RP-1/LOX propellant. The main body of the rocket is constructed using a lightweight carbon composite material."),
    
    RocketsItems(name: "Neutron", shortDescription: "Neutron features a reusable first stage designed to land on an ocean platform.", firstFactTitle: "Height", firstFactInfo: "40 m", secondFactTitle: "Diameter", secondFactInfo: "4.5 m", thirdFactTitle: "Stages", thirdFactInfo: "2", fourthFactTitle: "Thrust", fourthFactInfo: "Unknown yet...", descriptionParagraph1: "Neutron features a reusable first stage designed to land on an ocean platform, enabling a high launch cadence and decreased launch costs for customers.", descriptionParagraph2: "It will be reliable and cost-effective launch services for constellation deployment, cargo resupply, interplanetary missions. Human spaceflight capable.", descriptionParagraph3: "Launching From 2024."),
    
    RocketsItems(name: "Atlas V", shortDescription: "Delivers the most sensitive and critical missions", firstFactTitle: "Height", firstFactInfo: "58.3 m", secondFactTitle: "Diameter", secondFactInfo: "3.81 m", thirdFactTitle: "Stages", thirdFactInfo: "2 - 3", fourthFactTitle: "Thrust", fourthFactInfo: "1.688 MN", descriptionParagraph1: "Atlas V is an expendable launch system and the fifth major version in the Atlas rocket family. It was originally designed by Lockheed Martin, now being operated by United Launch Alliance (ULA), a joint venture between Lockheed Martin and Boeing.", descriptionParagraph2: "Each Atlas V rocket consists of two main stages. The first stage is powered by a Russian RD-180 engine manufactured by Energomash and burning kerosene and liquid oxygen. The Centaur upper stage is powered by one or two United States RL10 engine(s) manufactured by Aerojet Rocketdyne and burning liquid hydrogen and liquid oxygen. The Star 48 upper stage was used on the New Horizons mission as a third stage. AJ-60A strap-on solid rocket boosters (SRBs) are used in some configurations. In November 2020, they were replaced by the GEM-63 SRBs. The standard payload fairings are 4.2 or 5.4 m (14 or 18 ft) in diameter with various lengths.", descriptionParagraph3: "As of 13 November 2020, the rocket has a streak of 76 consecutive successful launches since the first ULA Atlas V launch on 11 October 2007."),
    
    RocketsItems(name: "Delta IV", shortDescription: "Proven heavy lift capability to deliver high-priority payloads to orbit.", firstFactTitle: "Height", firstFactInfo: "63 - 72 m", secondFactTitle: "Diameter", secondFactInfo: "5 m", thirdFactTitle: "Stages", thirdFactInfo: "2", fourthFactTitle: "Thrust", fourthFactInfo: "826.6 kN", descriptionParagraph1: "Delta IV is a group of five expendable launch systems in the Delta rocket family introduced in the early 2000s. Originally designed by Boeing's Defense, Space and Security division for the Evolved Expendable Launch Vehicle (EELV) program, the Delta IV became a United Launch Alliance (ULA) product in 2006. The Delta IV is primarily a launch vehicle for United States Air Force (USAF) military payloads, but has also been used to launch a number of United States government non-military payloads and a single commercial satellite. ", descriptionParagraph2: "The Delta IV originally had two main versions which allowed the family to cover a range of payload sizes and masses: the retired Medium (which had four configurations) and Heavy. As of 2019, only the Heavy remains active, with payloads that would previously fly on Medium moving to either the existing Atlas V or the forthcoming Vulcan. Retirement of the Delta IV is anticipated in 2023.", descriptionParagraph3: "Delta IV vehicles are built in the ULA facility in Decatur, Alabama. Final assembly is completed at the launch site by ULA: at the horizontal integration facility for launches from SLC-37B pad at Cape Canaveral and in a similar facility for launches from SLC-6 pad at Vandenberg Air Force Base. "),
    
    RocketsItems(name: "Delta II", shortDescription: "Over 29 years, the rocket launched 155 times with 100 consecutive successful missions", firstFactTitle: "Height", firstFactInfo: "38.9 m", secondFactTitle: "Diameter", secondFactInfo: "2.44 m", thirdFactTitle: "Stages", thirdFactInfo: "2 - 3", fourthFactTitle: "Thrust", fourthFactInfo: "478 kN", descriptionParagraph1: "Delta II was an expendable launch system, originally designed and built by McDonnell Douglas. Delta II was part of the Delta rocket family and entered service in 1989. Delta II vehicles included the Delta 6000, and the two later Delta 7000 variants ('Light' and 'Heavy'). The rocket flew its final mission ICESat-2 on 15 September 2018, earning the launch vehicle a streak of 100 successful missions in a row, with the last failure being GPS IIR-1 in 1997", descriptionParagraph2: "In the early 1980s, all United States expendable launch vehicles were planned to be phased out in favor of the Space Shuttle, which would be responsible for all government and commercial launches. Production of Delta, Atlas-Centaur, and Titan 34D had ended. The Challenger disaster of 1986 and the subsequent halt of Shuttle operations changed this policy, and President Ronald Reagan announced in December 1986 that the Space Shuttle would no longer launch commercial payloads, and NASA would seek to purchase launches on expendable vehicles for missions that did not require crew or Shuttle support.", descriptionParagraph3: "McDonnell Douglas, at that time the manufacturer of the Delta family, signed a contract with the U.S. Air Force in 1987 to provide seven Delta II. These were intended to launch a series of Global Positioning System (GPS) Block II satellites, which had previously been manifested for the Space Shuttle. The Air Force exercised additional contract options in 1988, expanding this order to 20 vehicles, and NASA purchased its first Delta II in 1990 for the launch of three Earth-observing satellites. The first Delta II launch occurred on 14 February 1989, with a Delta 6925 boosting the first GPS Block II satellite (USA-35) from Launch Complex 17A (SLC-17A) at Cape Canaveral into a 20,000 km high medium Earth orbit."),
    
    RocketsItems(name: "Vulcan Centaur", shortDescription: "Higher performance while continuing to deliver unmatched reliability and precision.", firstFactTitle: "Height", firstFactInfo: "61.6 m", secondFactTitle: "Diameter", secondFactInfo: "5.4 m", thirdFactTitle: "Stages", thirdFactInfo: "2", fourthFactTitle: "Thrust", fourthFactInfo: "N/A", descriptionParagraph1: "Vulcan Centaur is a two-stage-to-orbit heavy-lift launch vehicle under development 2014–2021 by United Launch Alliance (ULA), principally funded through the US government's National Security Space Launch (NSSL) competition and launch program, to meet the demands of the United States Space Force and US national security satellite launches.", descriptionParagraph2: "ulcan is ULA's first launch vehicle design, adapting and evolving various technologies previously developed for the Atlas V and Delta IV rockets of the USAF's EELV program. The first stage propellant tanks share the diameter of the Delta IV Common Booster Core, but will contain liquid methane and liquid oxygen propellants instead of the Delta IV's liquid hydrogen and liquid oxygen.", descriptionParagraph3: "Vulcan's upper stage is the Centaur V, an upgraded variant of the Common Centaur/Centaur III currently used on the Atlas V. A version of the RL-10 engine with an nozzle extension, the RL-10CX, will be used on the Vulcan Centaur Heavy.[3] Previous plans called for the Centaur V to be eventually upgraded with Integrated Vehicle Fluids technology to become the Advanced Cryogenic Evolved Stage (ACES), but full development of this upper-stage design was cancelled.[13] Vulcan is intended to undergo the human-rating certification process to allow the launch of crew, such as the Boeing CST-100 Starliner or a future crewed version of the Sierra Nevada Dream Chaser spaceplane.")
]
